# Generated by Django 2.0.1 on 2019-11-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_wallet_id', models.IntegerField(blank=True, null=True)),
                ('yk_user_id', models.IntegerField(blank=True, null=True)),
                ('yk_recharge_time', models.TimeField(blank=True, null=True)),
                ('yk_recharge_amount', models.FloatField(blank=True, null=True)),
                ('yk_consumption_time', models.TimeField(blank=True, null=True)),
                ('yk_consumption_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Downloadrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_dowtime', models.TimeField(blank=True, db_column='yk_dowTime', null=True)),
                ('yk_dowcontent', models.CharField(blank=True, db_column='yk_dowContent', max_length=50, null=True)),
                ('yk_u_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'downloadrecord',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_name', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('yk_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('yk_age', models.IntegerField(blank=True, null=True)),
                ('yk_career', models.CharField(blank=True, db_column='yk_Career', max_length=50, null=True)),
                ('yk_hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_idnumber', models.CharField(blank=True, db_column='yk_IDnumber', max_length=50, null=True)),
                ('yk_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('yk_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mycourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_user_id', models.IntegerField(blank=True, null=True)),
                ('yk_class_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mycourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_pay_pwd', models.CharField(blank=True, max_length=100, null=True)),
                ('yk_user_id', models.IntegerField(blank=True, null=True)),
                ('yk_bank_card', models.IntegerField(blank=True, null=True)),
                ('yk_integral', models.IntegerField(blank=True, null=True)),
                ('yk_member', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_discount', models.CharField(blank=True, max_length=10, null=True)),
                ('yk_paymentype', models.CharField(blank=True, db_column='yk_paymenType', max_length=5, null=True)),
                ('yk_transtype', models.CharField(blank=True, db_column='yk_transType', max_length=5, null=True)),
            ],
            options={
                'db_table': 'wallet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YkLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_video_jump_link', models.CharField(blank=True, max_length=200, null=True)),
                ('yk_lesson_name', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_lesson_price', models.FloatField(blank=True, null=True)),
                ('yk_lesson_describe', models.CharField(blank=True, max_length=200, null=True)),
                ('yk_teacher_describe', models.CharField(blank=True, max_length=100, null=True)),
                ('yk_lesson_contents', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_lesson_contents_mark', models.IntegerField(blank=True, null=True)),
                ('yk_lesson_img', models.CharField(blank=True, max_length=200, null=True)),
                ('yk_rotaion_id', models.IntegerField(blank=True, null=True)),
                ('yk_recommend_id', models.IntegerField(blank=True, null=True)),
                ('yk_lesson_price_type', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_lesson_dis_price', models.FloatField(blank=True, null=True)),
                ('yk_lesson_list', models.IntegerField(blank=True, null=True)),
                ('yk_user_id', models.IntegerField(blank=True, null=True)),
                ('yk_buy_amount', models.IntegerField(blank=True, null=True)),
                ('yk_watch_amount', models.IntegerField(blank=True, null=True)),
                ('yk_course_chapter', models.CharField(blank=True, max_length=20, null=True)),
                ('yk_one_list_id', models.IntegerField(blank=True, null=True)),
                ('yk_tow_list_id', models.IntegerField(blank=True, null=True)),
                ('yk_class_size', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'yk_lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_goods_id', models.IntegerField(blank=True, null=True)),
                ('yk_isorderstatus', models.IntegerField(blank=True, db_column='yk_isorderStatus', null=True)),
                ('yk_total_price', models.FloatField(blank=True, null=True)),
                ('yk_user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yk_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_name', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_auto_string', models.CharField(blank=True, max_length=100, null=True)),
                ('yk_emil', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_phone', models.IntegerField(blank=True, null=True)),
                ('sys_auth', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'yk_user',
                'managed': False,
            },
        ),
    ]
