# Generated by Django 2.0.1 on 2019-11-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firstclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_firstclassname', models.CharField(blank=True, db_column='yk_FirstClassName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'firstclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_video_jump_link', models.CharField(max_length=200)),
                ('yk_firstclassid', models.IntegerField(blank=True, db_column='yk_FirstClassID', null=True)),
                ('yk_secondclassid', models.IntegerField(blank=True, db_column='yk_SecondClassID', null=True)),
                ('yk_lesson_name', models.CharField(blank=True, max_length=50, null=True)),
                ('yk_lesson_price', models.FloatField(blank=True, null=True)),
                ('yk_lesson_describe', models.CharField(blank=True, max_length=200, null=True)),
                ('yk_teacher_describe', models.CharField(blank=True, max_length=100, null=True)),
                ('yk_lesson_contents', models.CharField(max_length=50)),
                ('yk_lesson_contents_mark', models.IntegerField()),
                ('yk_lesson_image', models.CharField(blank=True, max_length=256, null=True)),
                ('yk_rotation_id', models.IntegerField(blank=True, null=True)),
                ('yk_recommend_lesson_id', models.IntegerField(blank=True, null=True)),
                ('yk_price_class', models.IntegerField(blank=True, null=True)),
                ('yk_discount_price', models.FloatField(blank=True, null=True)),
                ('yk_lesson_list_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessonlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_clicks', models.IntegerField(blank=True, db_column='yk_Clicks', null=True)),
                ('yk_ageclass', models.IntegerField(blank=True, db_column='yk_AgeClass', null=True)),
                ('yk_secondclassid', models.IntegerField(blank=True, db_column='yk_SecondClassID', null=True)),
            ],
            options={
                'db_table': 'lessonlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secondclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_secondclassname', models.CharField(blank=True, db_column='yk_SecondClassName', max_length=20, null=True)),
                ('yk_firstclassid', models.IntegerField(blank=True, db_column='yk_FirstClassID', null=True)),
                ('yk_jumplink', models.CharField(blank=True, db_column='yk_JumpLink', max_length=256, null=True)),
                ('yk_likenumber', models.IntegerField(blank=True, db_column='yk_LikeNumber', null=True)),
            ],
            options={
                'db_table': 'secondclass',
                'managed': False,
            },
        ),
    ]
