# Generated by Django 2.0.1 on 2019-11-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_ls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstclass',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lessonlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='secondclass',
            options={},
        ),
    ]
