# Generated by Django 2.0.1 on 2019-11-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yk_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YKUser',
            fields=[
                ('ykuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yk_models.YkUser')),
            ],
            bases=('yk_models.ykuser',),
        ),
    ]
